version: '3'
services:
  server:
    container_name: server-app
    image: server-app:1.0
    build: 
      context: server
      dockerfile: Dockerfile

    ports:
     - 4000:4000

    depends_on:
     - "mongodb"

  client:
    container_name: client-app
    image: client-app:1.0
    build: 
      context: client
      dockerfile: Dockerfile

    ports:
     - 3000:3000

    depends_on:
     - "server"

  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
     - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8080:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
     - "mongodb"
volumes:
  mongo-data:
    driver: local